

name: Release
on:
  workflow_run:
    workflows: [Build Java]
    types:
      - completed

jobs:
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v3
      with:
        name: build/lib/Artifacts
        
    - name: Display structure of downloaded files
      run: ls -R

