

name: Release
on:
  workflow_run:
    workflows: 
      - Build Java
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v3
      with:
          name: Artifacts
          path: build/libs/
        
    - name: Display structure of downloaded files
      run: ls -R

